citra_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import pasien.urls
import nilai_normal.urls
import uji_lab.urls
import dokter.urls
import tester.urls
import pemeriksaan.urls
import bidang.urls
import uji_lab.urls
import hasil_pemeriksaan.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='pasien/', permanent=True)),
    path('home/', include(main.urls)),
    path('pasien/', include(pasien.urls)),
    path('nilai_normal/', include(nilai_normal.urls)),
    path('ujilab/', include(uji_lab.urls)),
    path('pemeriksaan/', include(pemeriksaan.urls)),
    path('dokter/', include(dokter.urls)),
    path('tester/', include(tester.urls)),
    path('bidang/', include(bidang.urls)),
    path('uji_lab/', include(uji_lab.urls)),
    path('hasil_pemeriksaan/', include(hasil_pemeriksaan.urls)),
    
]

main/urls.py
from django.urls import path
from .views import *

app_name= 'main'
urlpatterns = [
    path('', index, name='index'),
]

tester/urls.py
from django.urls import path
from .views import *

app_name= 'tester'
urlpatterns = [
    path('', all_tester, name='all_tester'),
    path('add', add_tester, name='add_tester'),
    path('edit/<str:id>', edit_tester, name='edit_tester'),
    path('delete/<str:id>', delete_tester, name='delete_tester')
]

tester/models.py
from django.db import models

# Create your models here.
class Tester(models.Model):
    kode = models.CharField(max_length=100)
    nama = models.CharField(max_length=150)
    pemeriksaan_on_proses = models.IntegerField(default=0)
    pemeriksaan_selesai = models.IntegerField(default=0)
    total_pemeriksaan = models.IntegerField(default=0)

tester/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *

# Landing pertama ketika membuka halaman tester
response ={'lab_name' : 'citra'}
def index(request):
    return render(request, 'index.html')

# function untuk menambahkan tester baru
def add_tester(request):
    testers = Tester.objects.all()
    tmp = testers.count()+1
    if request.method == 'POST':
        kode = 'TST' + str(tmp)
        nama = request.POST.get('nama_tester')
        model = Tester(kode = kode, nama = nama)
        model.save()
        return HttpResponseRedirect(reverse('tester:all_tester'))
    else:
        return HttpResponseRedirect(reverse('tester:all_tester'))

# function untuk mengedit object tester
def edit_tester(request, id):
    person = Tester.objects.get(kode = id)
    if request.method == 'POST':
        person.nama = request.POST.get('nama_tester')
        person.save()
    return HttpResponseRedirect(reverse('tester:all_tester'))

# function untuk menghapus tester
def delete_tester(request, id=None):
    obj_tester = Tester.objects.get(id=1)
    obj_tester.delete()
    return render(render, 'index.html')

# function untuk menampilkan semua tester
def all_tester(request):
    testers = Tester.objects.all()
    flag_null = True
    if testers.count() != 0:
        flag_null = False
    response["testers"] = testers
    response["flag_null"] = flag_null
    return render(request, 'lp_tester.html', response)

tester/templates/lp_tester.html
{% extends 'layout/base.html' %} 
{% load static %} 
{% block title %} Dokter {% endblock title %} 

{% block css %}

{% endblock css %}

{% block navbar_link %}
  Tester
{% endblock navbar_link %}

{% block navbar_title %}
 Daftar Tester
{% endblock navbar_title %}

{% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <div>
      <div>
        <button type="button" class="btn btn-block bg-gradient-info mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-tester">
            <i class="material-icons opacity-10">add_circle_outline</i><span>Tambahkan Tester</span></button>
      </div>
      <div>
        <div class="modal fade" id="modal-form-tester" tabindex="-1" role="dialog" aria-labelledby="modal-form-tester" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-m" role="document">
            <div class="modal-content">
              <div class="modal-body p-0">
                <div class="card card-plain">
                  <div class="card-header pb-0 text-left">
                    <h5 class="">Tambahkan Tester Baru</h5>
                    <p class="mb-0">Masukkan data Tester</p>
                  </div>
                  <div class="card-body m-0">
                  <!-- Form mrnambahkan pasien baru-->
                    <form class="form text-left was-validated" method="POST" action="{% url 'tester:add_tester' %}" id="tambah_tester">
                      {% csrf_token %}
                      <!--
                      <div class="input-group input-group-static my-3">
                        <label class="" for="ukode">Kode Tester</label>
                        <input type="text" class="form-control" id="ukode" name="kode" required>
                        <div class="valid-feedback" >Good!</div>
                        <div class="invalid-feedback">Tolong isi bagian ini.</div>
                      </div>
                      
                      <div class="input-group input-group-static my-3">
                          <label class="" for="uname">Nama Tester</label>
                          <input type="text" id="uname" class="form-control" name="nama" required>
                          <div class="valid-feedback">Good!</div>
                          <div class="invalid-feedback">Tolong isi bagian ini.</div>
                      </div>
                      -->
                      <div class="input-group input-group-dynamic mb-4">
                        <input type="text" id="uname" class="form-control" placeholder="Nama Tester" aria-label="nama_tester" name="nama_tester" required>
                        <div class="valid-feedback">Nama tester valid!</div>
                        <div class="invalid-feedback">Masukkan nama tester di sini.</div>
                    </div>
                      <div class="text-center">
                        <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Simpan</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <div class="row">
            <div class="col-12">
              <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                  <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Daftar Tester</h6>
                  </div>
                </div>
                <div class="card-body px-0 pb-2">
                    {% if flag_null %}
                    <div class="h5 text-center">
                        Tidak ada data tester untuk saat ini.
                    </div>
                    {% else %}
                  <div class="table-responsive p-0">
                    <table id="pasienTable" class="table align-items-center mb-0 table-paginate" cellspacing="0">
                      <thead>
                        <tr>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">Kode Tester</th>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 text-center">Nama Tester</th>
                          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">On proses</th>
                          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">Jumlah Pemeriksaan</th>
                          <th class="text-secondary opacity-7"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for tester in testers %}
                        <tr class="text-center">
                          <td class="text-center">
                            <p class="text-xs font-weight-bold mb-0">{{tester.kode}}</p>
                          </td>
                          <td class="text-center">
                            <p class="text-xs font-weight-bold mb-0">{{tester.nama}}</p>
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0">{{tester.pemeriksaan_on_proses}}</p>
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0">{{tester.total_pemeriksaan}}</p>
                          </td>
                          
                          <td class="align-middle text-center">
                            
                            <div>
                              <button type="button" class="btn btn-block bg-gradient-secondary mb-3" data-bs-toggle="modal" data-bs-target="#modal-edit-{{tester.kode}}">
                                  <i class="material-icons opacity-10">edit</i><span> edit</span></button>
                            </div>
                            <!-- Modal untuk Edit-->
                            <div class="modal fade" id="modal-edit-{{tester.kode}}" tabindex="-1" role="dialog" aria-labelledby="modal-edit-{{tester.kode}}" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered modal-m" role="document">
                                <div class="modal-content">
                                  <div class="modal-body p-0">
                                    <div class="card card-plain">
                                      <div class="card-header pb-0 text-left">
                                        <h5 class="">Edit Data Tester</h5>
                                        <p class="mb-0">Masukkan data tester baru</p>
                                      </div>
                                      <div class="card-body">
                                      <!-- Form mrnambahkan pasien baru-->
                                        <form class="form text-left was-validated" method="POST" action="{% url 'tester:edit_tester' id=tester.kode %}" id="edit_tester">
                                          {% csrf_token %}  
                                          <div class=" input-group input-group-outline my-3" style="text-align: left;">
                                            <input type="text" class="form-control" id="editkode{{tester.kode}}" name="kode" value="{{tester.kode}}" required disabled>
                                            <div class="valid-feedback" >Good!</div>
                                            <div class="invalid-feedback">Tolong isi bagian ini.</div>
                                          </div>
                                          <div class="input-group input-group-static my-3" style="text-align: left;">
                                              <label class="" for="editnama{{tester.kode}}">Nama Tester</label>
                                              <input type="text" id="editnama{{tester.kode}}" class="form-control" name="nama_tester" value="{{tester.nama}}" required>
                                              <div class="valid-feedback">Nama tester valid!</div>
                                              <div class="invalid-feedback">Masukkan nama tester di sini.</div>
                                          </div>
                                          <div class="text-center">
                                            <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Edit</button>
                                          </div>
                                        </form>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock content %}