citra_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import pasien.urls
import nilai_normal.urls
import uji_lab.urls
import dokter.urls
import tester.urls
import pemeriksaan.urls
import bidang.urls
import uji_lab.urls
import hasil_pemeriksaan.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='pasien/', permanent=True)),
    path('home/', include(main.urls)),
    path('pasien/', include(pasien.urls)),
    path('nilai_normal/', include(nilai_normal.urls)),
    path('ujilab/', include(uji_lab.urls)),
    path('pemeriksaan/', include(pemeriksaan.urls)),
    path('dokter/', include(dokter.urls)),
    path('tester/', include(tester.urls)),
    path('bidang/', include(bidang.urls)),
    path('uji_lab/', include(uji_lab.urls)),
    path('hasil_pemeriksaan/', include(hasil_pemeriksaan.urls)),
    
]

main/urls.py
from django.urls import path
from .views import *

app_name= 'main'
urlpatterns = [
    path('', index, name='index'),
]

pasien/urls.py
from django.urls import path
from .views import *

app_name= 'pasien'
urlpatterns = [
    path('', all_pasien, name='all_pasien'),
    path('add/', add_pasien, name='add_pasien'),
    path('edit/<str:id>', edit_pasien, name='edit_pasien'),
    path('delete/<str:id>', delete_pasien, name='delete_pasien'),
    path('view/<str:id>', view_pasien, name='view_pasien'),
]

uji_lab/urls.py
from django.urls import path
from .views import *

app_name= 'uji_lab'
urlpatterns = [
    path('', all_uji_lab, name='all_uji_lab'),
    path('add/', add_uji_lab, name='add_uji_lab'),
    path('edit/<str:id>', edit_uji_lab, name='edit_uji_lab'),
    path('delete/<str:id>', delete_uji_lab, name='delete_uji_lab'),
    path('view/<str:id>', view_uji_lab, name='view_uji_lab'),
]

main/models.py
from django.db import models

# Create your models here.

pasien/models.py
from django.db import models

# Create your models here.
class Pasien(models.Model):
    uid = models.CharField(max_length=100)
    nama = models.CharField(max_length=100)
    tanggal_lahir = models.DateField()
    umur = models.CharField(max_length=50)
    jenis_kelamin = models.BooleanField()
    alamat = models.CharField(max_length=250)
    tanggal_mendaftar = models.DateField()
    diagnosa_awal = models.CharField(max_length=250)

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main.html')

pasien/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import *
from datetime import date
from django.utils.dateparse import parse_date
import random
import string
from uji_lab.models import *
from pemeriksaan.models import *
from dokter.models import *
from tester.models import *
from bidang.models import *
from json import dumps
from django.core import serializers
import json

'''

'''

# Register Pasien Views.
response ={'lab_name' : 'citra'}

def calculate_age(birthdate):
    tmp = parse_date(birthdate)
    today = date.today()
    age = today.year - tmp.year - ((today.month, today.day) < (tmp.month, tmp.day))
    return age

def uid_generator():
    random_string = ''.join(random.choices(string.ascii_uppercase, k=5))
    count = Pasien.objects.all().count()
    tmp = "LC" + str(count) + random_string
    return tmp

def add_pasien(request):
    # get register form
    if request.method == 'POST':
        uid = uid_generator()
        nama = request.POST.get("nama")
        tanggal_lahir = request.POST.get("tanggal_lahir")
        umur = calculate_age(tanggal_lahir)
        jenis_kelamin = None
        if request.POST.get("jenis_kelamin") == "true":
            jenis_kelamin = True
        else:
            jenis_kelamin = False
        alamat = request.POST.get("alamat")
        tanggal_mendaftar = date.today()
        diagnosa_awal = "None"
        model = Pasien(uid=uid, nama=nama, tanggal_lahir = tanggal_lahir, umur=umur, jenis_kelamin=jenis_kelamin, alamat=alamat, tanggal_mendaftar=tanggal_mendaftar, diagnosa_awal=diagnosa_awal)
        model.save()
    return HttpResponseRedirect(reverse('pasien:all_pasien'))


# List pasien views
def all_pasien(request):
    data_pasien = Pasien.objects.all()
    flag_null = True
    if data_pasien.count() != 0:
        flag_null = False
    response['flag_null'] = flag_null
    response['data_pasien'] = data_pasien
    return render(request, 'lp_pasien.html', response)

# Edit pasien views
def edit_pasien(request, id):
    person = Pasien.objects.get(uid=id)
    edit_success =True
    return render(request, 'main.html', response)


# Arsipkan pasien views
def delete_pasien(request, id):
    person = Pasien.objects.get(uid=1)
    delete_success = True
    return render(request, 'main.html', response)


# View profile views
def view_pasien(request, id):
    person = Pasien.objects.get(uid=id)
    pemeriksaan = Pemeriksaan.objects.filter(id_pasien=id)
    bidang = Bidang.objects.all()
    dokter = Dokter.objects.all()
    tester = Tester.objects.all()
    
    for tmp in bidang:
        uji_lab = UjiLab.objects.filter(id_bidang = tmp.uid)
        # create json
        tmpJson = serializers.serialize("json",uji_lab)
        tmpObj = json.loads(tmpJson)
        response[tmp.uid] = dumps(tmpObj)
    response['person'] = person
    flag_null = True
    if pemeriksaan.count() != 0:
        flag_null = False
    # make json
    tmpJson2 = serializers.serialize("json",bidang)
    tmpObj2 = json.loads(tmpJson2)
    
    response["count"] = dumps(tmpObj2)
    response['flag_null'] = flag_null
    response['datas'] = pemeriksaan
    response['bidang'] = bidang
    response['dokter'] = dokter
    response['tester'] = tester
    return render(request, 'lp_profile.html', response)

pasien/templates/lp_pasien.html
{% extends 'layout/base.html' %} 
{% load static %} 
{% block title %} Pasien {% endblock title %} 

{% block css %}

{% endblock css %}

{% block navbar_link %}
  Pasien
{% endblock navbar_link %}

{% block navbar_title %}
 Daftar Pasien
{% endblock navbar_title %}

{% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <div>
      <div>
        <button type="button" class="btn btn-block bg-gradient-info mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-pasien">
            <i class="material-icons opacity-10">add_circle_outline</i><span> Tambahkan Pasien</span></button>
      </div>
      <div>
        <div class="modal fade" id="modal-form-pasien" tabindex="-1" role="dialog" aria-labelledby="modal-form-pasien" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-m" role="document">
            <div class="modal-content">
              <div class="modal-body p-0">
                <div class="card card-plain">
                  <div class="card-header pb-0 text-left">
                    <h5 class="">Tambahkan Pasien Baru</h5>
                    <p class="mb-0">Masukkan data pasien</p>
                  </div>
                  <div class="card-body m-0">
                  <!-- Form mrnambahkan pasien baru-->
                    <form class="form text-left was-validated" method="POST" action="{% url 'pasien:add_pasien' %}" id="tambah_pasien">
                      {% csrf_token %}
                      <div class="input-group input-group-dynamic mb-4">
                        <input type="text" class="form-control" id="nama" name="nama" placeholder="Nama Pasien" required>
                        <div class="valid-feedback">Pastinakan nama sesuai dengan KTP!</div>
                        <div class="invalid-feedback">Masukkan nama pasien di sini.</div>
                      </div>
                      <div class="input-group input-group-dynamic mb-4">
                        <input type="date" class="form-control" id="tanggal_lahir" name="tanggal_lahir" placeholder="Tanggal Lahir 'dd/mm/yy'" required>
                        <div class="valid-feedback">Pastinakan tanggal lahir sesuai dengan KTP!</div>
                        <div class="invalid-feedback">Masukkan tanggal lahir pasien di sini.</div>
                      </div>
                      <div class="">
                        <div class="form-check mb-3">
                          <input class="form-check-input" type="radio" name="jenis_kelamin" value="true" id="customRadio1" required> 
                          <label class="custom-control-label" for="customRadio1">Laki-laki</label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="radio" name="jenis_kelamin" value="false" id="customRadio2" required>
                          <label class="custom-control-label" for="customRadio2">Perempuan</label>
                          <div class="invalid-feedback">Pilih jenis kelamin pasien</div>
                        </div>
                      </div>
                      <div class="input-group input-group-dynamic mb-4">
                        <textarea class="form-control" id="alamat" name="alamat" placeholder="Masukkan alamat pasien . . ." required></textarea>
                        <div class="valid-feedback">Pastikan alamat paseien sesuai dengan KTP!</div>
                        <div class="invalid-feedback">Masukkan alamat pasien di sini.</div>
                      </div>
                      <div class="text-center">
                      <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Simpan</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <div class="row">
            <div class="col-12">
              <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                  <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Daftar Pasien</h6>
                  </div>
                </div>
                <div class="card-body px-0 pb-2">
                    {% if flag_null %}
                    <div class="h5 text-center">
                        Tidak ada data pasien untuk saat ini.
                    </div>
                    {% else %}
                  <div class="table-responsive p-0">
                    <table id="pasienTable" class="table align-items-center mb-0 table-paginate" cellspacing="0">
                      <thead>
                        <tr>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Kode</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Nama</th>
                            <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Tanggal Lahir</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Jenis Kelamin</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Alamat</th>
                            <th class="text-secondary opacity-7"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for person in data_pasien %}
                            <tr>
                                <td>
                                    <p class="text-xs font-weight-bold mb-0">{{person.uid}}</p>
                                  </td>
                              <td>
                                <div class="d-flex px-2 py-1">
                                  <div class="d-flex flex-column justify-content-center">
                                    <h6 class="mb-0 text-sm font-weight-bold mb-0">{{person.nama}}</h6>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <p class="text-xs font-weight-bold mb-0">{{person.tanggal_lahir}}</p>
                              </td>
                              {% if person.jenis_kelamin %}
                              <td class="align-middle text-center">
                                <p class="text-xs font-weight-bold mb-0">Laki-laki</p>
                              </td>
                              {% else %}
                              <td class="align-middle text-center">
                                <p class="text-xs font-weight-bold mb-0">Perempuan</p>
                              </td>
                              {% endif %}
                              <td class="align-middle text-center">
                                <p class="text-xs font-weight-bold mb-0">{{person.alamat}}</p>
                              </td>
                              <td class="align-middle text-center">
                                <a href="{% url 'pasien:view_pasien' id=person.uid %}" class="btn btn-info font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                  lihat
                                </a>
                              </td>
                            </tr>
                            
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock content %}

pasien/templates/profile.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Diri Pasien</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- {% static 'css/display_barang.css' %} -->
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->
    <!-- CSS Files -->
    <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
</head>
<body>
    <div>


        <!--konten-->
        <div>
            <div class="container-fluid px-2 px-md-4">
                <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
                  <span class="mask  bg-gradient-primary  opacity-6"></span>
                </div>
                <div class="card card-body mx-3 mx-md-4 mt-n6">
                  <div class="row gx-4 mb-2">
                    <div class="col-auto">
                      <div class="avatar avatar-xl position-relative">
                        <img src="{% static 'img/person.jpg' %}" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
                      </div>
                    </div>
                    <div class="col-auto my-auto">
                      <div class="h-100">
                        <h5 class="mb-1">
                          {{person.nama}}
                        </h5>
                        <p class="mb-0 font-weight-normal text-sm">
                          {{person.tanggal_mendaftar}}
                        </p>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="row">
                      <div class="col-12 col-xl-4">
                        <div class="card card-plain h-100">
                          <div class="card-header pb-0 p-3">
                            <h6 class="mb-0">Data Diri</h6>
                          </div>
                          <div class="card-body p-3">
                            <hr class="horizontal gray-light my-2">
                            <ul class="list-group">
                                <li class="list-group-item border-0 ps-0 pt-0 text-sm"><strong class="text-dark">Tanggal Lahir  :</strong> &nbsp; {{person.tanggal_lahir}}</li>
                                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Umur  :</strong> &nbsp; {{person.umur}} tahun</li>
                                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">No. Hp  :</strong> &nbsp; (62) 889 8987 9737</li>
                              </ul>
                          </div>
                        </div>
                      </div>
                      <div class="col-12 col-xl-4">
                        <div class="card card-plain h-100">
                          <div class="card-header pb-0 p-3">
                            <div class="row">
                              <div class="col-md-8 d-flex align-items-center">
                                <h6 class="mb-0">Alamat Lengkap</h6>
                              </div>
                              
                              <div class="col-md-4 text-end">
                                <a href="javascript:;">
                                  <i class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Profile"></i>
                                </a>
                              </div>
                            </div>
                          </div>
                          <div class="card-body p-3">
                            <hr class="horizontal gray-light my-2">
                            <p class="text-sm">
                              {{person.alamat}}
                            </p>
                          </div>
                        </div>
                      </div>
                      
                      <div class="col-12 mt-4">
                        <div class="mb-1 ps-3">
                          <h6 class="mb-1">Daftar Pemeriksaan</h6>
                          <p class="text-sm">Daftar pemeriksaan pasien di lab citra.</p>
                          <a href="{% url 'uji_lab:add_uji_lab' %}">
                            <button type="button" class="btn btn-block bg-gradient-info mb-2 active"  style="text-transform: uppercase !important; color: white;" data-bs-toggle="modal" data-bs-target="#modal-form">
                                <i class="material-icons opacity-10">post_add</i>
                                <span>Tambah Pemeriksaan</span>
                            </button>
                          </a>
                            <a class="nav-link mb-0 px-0 py-1 active " data-bs-toggle="tab" href="{% url 'uji_lab:add_uji_lab' id=person.uid %}" role="tab" aria-selected="true">
                                <i class="material-icons text-lg position-relative">home</i>
                                <span class="ms-1">Tamba Pemeriksaan</span>
                            </a>
                        </div>
                        
                        <div class="row">
                            <div class="card my-4">
                                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                                      <h6 class="text-white text-capitalize ps-3">Daftar Pemeriksaan</h6>
                                    </div>
                                </div>
                                {% if flag_null %}
                                <div class="h5 text-center m-2">
                                    Pasien belum pernah melakukan pemeriksaan.
                                </div>
                                {% else %}
                                <div class="table-responsive">
                                  <table class="table align-items-center mb-0">
                                    <thead>
                                      <tr>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Author</th>
                                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Function</th>
                                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Technology</th>
                                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Employed</th>
                                        <th class="text-secondary opacity-7"></th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <tr>
                                        {% for data in data_lab %}
                                        <td>
                                          <div class="d-flex px-2 py-1">
                                            <div>
                                              <img src="https://demos.creative-tim.com/test/material-dashboard-pro/assets/img/team-2.jpg" class="avatar avatar-sm me-3">
                                            </div>
                                            <div class="d-flex flex-column justify-content-center">
                                              <h6 class="mb-0 text-xs">John Michael</h6>
                                              <p class="text-xs text-secondary mb-0">john@creative-tim.com</p>
                                            </div>
                                          </div>
                                        </td>
                                        <td>
                                          <p class="text-xs font-weight-bold mb-0">Manager</p>
                                          <p class="text-xs text-secondary mb-0">Organization</p>
                                        </td>
                                        <td class="align-middle text-center text-sm">
                                          <span class="badge badge-sm badge-success">Online</span>
                                        </td>
                                        <td class="align-middle text-center">
                                          <span class="text-secondary text-xs font-weight-normal">23/04/18</span>
                                        </td>
                                        <td class="align-middle">
                                          <a href="javascript:;" class="text-secondary font-weight-normal text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                            Edit
                                          </a>
                                        </td>
                                        {% endfor %}
                                      </tr>
                                    </tbody>
                                  </table>
                                </div>
                                {% endif %}
                              </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        </div>
    </div>


    <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/searchBuilder.bootstrap5.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    
  
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js?v=3.1.0' %}"></script>

    <script>
    $(document).ready(function() {
        $('#pasienTable').dataTable();
     } );
    </script>
</body>
</html>