citra_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import pasien.urls
import nilai_normal.urls
import uji_lab.urls
import dokter.urls
import tester.urls
import pemeriksaan.urls
import bidang.urls
import uji_lab.urls
import hasil_pemeriksaan.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='pasien/', permanent=True)),
    path('home/', include(main.urls)),
    path('pasien/', include(pasien.urls)),
    path('nilai_normal/', include(nilai_normal.urls)),
    path('ujilab/', include(uji_lab.urls)),
    path('pemeriksaan/', include(pemeriksaan.urls)),
    path('dokter/', include(dokter.urls)),
    path('tester/', include(tester.urls)),
    path('bidang/', include(bidang.urls)),
    path('uji_lab/', include(uji_lab.urls)),
    path('hasil_pemeriksaan/', include(hasil_pemeriksaan.urls)),
    
]

dokter/urls.py
from django.urls import path
from .views import *

app_name= 'dokter'
urlpatterns = [
    path('', all_dokter, name='all_dokter'),
    path('add', add_dokter, name='add_dokter'),
    path('edit/<str:id>', edit_dokter, name='edit_dokter'),
    path('delete/<str:id>', delete_dokter, name='delete_dokter'),
    path('view/<str:id>', view_dokter, name='view_dokter'),
]

main/urls.py
from django.urls import path
from .views import *

app_name= 'main'
urlpatterns = [
    path('', index, name='index'),
]

dokter/models.py
from django.db import models

# Create your models here.
class Dokter(models.Model):
    kode_dokter = models.CharField(max_length=100)
    nama = models.CharField(max_length=100)
    komisi_dokter = models.IntegerField(default=0)
    komisi_belum_dibayar = models.IntegerField(default=0)
    komisi_sudah_dibayar = models.IntegerField(default=0)

dokter/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


from dokter.models import *

# Create your views here.
response ={'lab_name' : 'citra'}
def add_dokter(request):
    if request.method == 'POST':
        kode_dokter = request.POST.get("kode_dokter")
        nama = request.POST.get("nama_dokter")
        komisi_dokter = request.POST.get("komisi_dokter")
        komisi_belum_dibayar = 0
        komisi_sudah_sibayar = 0
        model = Dokter(kode_dokter=kode_dokter, nama=nama,komisi_dokter=komisi_dokter, komisi_belum_dibayar = komisi_belum_dibayar, komisi_sudah_dibayar=komisi_sudah_sibayar)
        model.save()
    return HttpResponseRedirect(reverse('dokter:all_dokter'))

def delete_dokter(request, id):
    person = Dokter.objects.get(kode_dokter = id)
    person.delete()
    return HttpResponseRedirect(reverse('dokter:all_dokter'))

def all_dokter(request):
    docters = Dokter.objects.all()
    flag_null = True
    if docters.count() != 0:
        flag_null = False
    response["doctors"] = docters
    response["flag_null"] = flag_null
    return render(request, 'landing_page_dokter.html', response)

def edit_dokter(request, id):
    person = Dokter.objects.get(kode_dokter = id)
    if request.method == 'POST':
        person.kode_dokter = request.POST.get("kode_dokter")
        person.nama = request.POST.get("nama_dokter")
        person.komisi_dokter = request.POST.get("komisi_dokter")
        person.save()
    return HttpResponseRedirect(reverse('dokter:all_dokter'))

def update_komisi_dokter(request, id):
    person = Dokter.objects.get(kode_dokter = id)
    person.komisi_sudah_dibayar = person.komisi_sudah_dibayar + person.komisi_belum_dibayar
    person.komisi_belum_dibayar = 0
    person.save()
    return HttpResponseRedirect(reverse('dokter:all_dokter'))

def view_dokter(request, id):
    return render(request, 'index.html', response)

dokter/templates/landing_page_dokter.html
{% extends 'layout/base.html' %} 
{% load static %} 
{% block title %} Dokter {% endblock title %} 

{% block css %}

{% endblock css %}

{% block navbar_link %}
  Dokter
{% endblock navbar_link %}

{% block navbar_title %}
 Daftar Dokter
{% endblock navbar_title %}

{% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <div>
      <div>
        <button type="button" class="btn btn-block bg-gradient-info mb-3" data-bs-toggle="modal" data-bs-target="#modal-form-dokter">
            <i class="material-icons opacity-10">add_circle_outline</i><span>Tambahkan Dokter</span></button>
      </div>
      <div>
        <div class="modal fade" id="modal-form-dokter" tabindex="-1" role="dialog" aria-labelledby="modal-form-dokter" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-m" role="document">
            <div class="modal-content">
              <div class="modal-body p-0">
                <div class="card card-plain">
                  <div class="card-header pb-0 text-left">
                    <h5 class="">Tambahkan Dokter Baru</h5>
                    <p class="mb-0">Masukkan data dokter</p>
                  </div>
                  <div class="card-body m-0">
                  <!-- Form mrnambahkan pasien baru-->
                    <form class="form text-left was-validated" method="POST" action="{% url 'dokter:add_dokter' %}" id="tambah_pasien">
                      {% csrf_token %}
                      <div class="input-group input-group-dynamic mb-4">
                        <input type="text" class="form-control" placeholder="Kode Dokter" id="ukode" aria-label="kode_dokter" name="kode_dokter" required>
                        <div class="valid-feedback">Kode dokter berhasil dimasukkan!</div>
                        <div class="invalid-feedback">Masukkan kode dokter di sini.</div>
                      </div>
                      <div class="input-group input-group-dynamic mb-4">
                          <input type="text" id="uname" class="form-control" placeholder="Nama Dokter" aria-label="nama_dokter" name="nama_dokter" required>
                          <div class="valid-feedback">Nama dokter berhasil dimasukkan!</div>
                          <div class="invalid-feedback">Masukkan nama dokter di sini</div>
                      </div>
                      <div class="input-group input-group-dynamic mb-4">
                        <span class="input-group-text" id="basic-addon1">@</span>
                        <input type="number" class="form-control" placeholder="Komisi Dokter" aria-label="komisi_dokter" name="komisi_dokter" aria-describedby="basic-addon1" required>
                        <div class="valid-feedback">Komisi berhasil dimasukkan!</div>
                        <div class="invalid-feedback">Masukkan komisi dokter di sini</div>
                      </div>
                      <!--
                      <div class="input-group input-group-dynamic mb-4">
                        <label class="" for="komisi_dokter">Komisi Dokter</label>
                        <span class="input-group-text" id="basic-addon1">%</span>
                        <input type="text" id="komisi_dokter" class="form-control" name="komisi_dokter" aria-label="komisi_dokter" aria-describedby="basic-addon1" required>
                        <div class="valid-feedback">Good!</div>
                        <div class="invalid-feedback">Masukkan nama dokter di sini</div>
                      </div>-->
                      <div class="text-center">
                        <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Simpan</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <div class="row">
            <div class="col-12">
              <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                  <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                    <h6 class="text-white text-capitalize ps-3">Daftar Dokter</h6>
                  </div>
                </div>
                <div class="card-body px-0 pb-2">
                    {% if flag_null %}
                    <div class="h5 text-center">
                        Tidak ada data dokter.
                    </div>
                    {% else %}
                  <div class="table-responsive p-0">
                    <table id="pasienTable" class="table align-items-center mb-0 table-paginate" cellspacing="0">
                      <thead>
                        <tr>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">Kode Dokter</th>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 text-center">Nama Dokter</th>
                          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 text-center">Komisi Dokter</th>
                          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">Komisi Sudah Dibayar</th>
                          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 text-center">Komisi Belum Dibayar</th>
                          <th class="text-secondary opacity-7"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for dokter in doctors %}
                        <tr class="text-center">
                          <td class="text-center">
                            <p class="text-xs font-weight-bold mb-0">{{dokter.kode_dokter}}</p>
                          </td>
                          <td class="text-center">
                            <p class="text-xs font-weight-bold mb-0">{{dokter.nama}}</p>
                          </td>
                          <td class="text-center">
                            <p class="text-xs font-weight-bold mb-0">{{dokter.komisi_dokter}} <span> %</span></p> 
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0"><span>Rp. </span>{{dokter.komisi_sudah_dibayar}}</p>
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0"><span>Rp. </span>{{dokter.komisi_belum_dibayar}}</p>
                          </td>
                          <td class="align-middle text-center">
                            <!--
                            <a href="{% url 'dokter:view_dokter' id=dokter.kode_dokter %}" class="btn btn-info font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                              lihat
                            </a>-->
                            <div>
                              <button type="button" class="btn btn-block bg-gradient-secondary mb-3" data-bs-toggle="modal" data-bs-target="#modal-edit-{{dokter.kode_dokter}}">
                                  <i class="material-icons opacity-10">edit</i><span> edit</span></button>
                            </div>
                            <!-- Modal untuk Edit-->
                            <div class="modal fade" id="modal-edit-{{dokter.kode_dokter}}" tabindex="-1" role="dialog" aria-labelledby="modal-edit-{{dokter.kode_dokter}}" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered modal-m" role="document">
                                <div class="modal-content">
                                  <div class="modal-body p-0">
                                    <div class="card card-plain">
                                      <div class="card-header pb-0 text-left">
                                        <h5 class="">Edit Data Dokter</h5>
                                        <p class="mb-0">Masukkan data dokter baru</p>
                                      </div>
                                      <div class="card-body text-left">
                                      <!-- Form mrnambahkan pasien baru-->
                                        <form class="form text-left was-validated" method="POST" action="{% url 'dokter:edit_dokter' id=dokter.kode_dokter %}" id="edit_dokter">
                                          {% csrf_token %}  
                                          <div class=" input-group input-group-outline my-3" style="text-align: left;">
                                            <!--<label class="" for="editkode{{dokter.kode_dokter}}">Kode Dokter</label>-->
                                            <input type="text" class="form-control" id="editkode{{dokter.kode_dokter}}" name="kode_dokter" value="{{dokter.kode_dokter}}" disabled required>
                                            <div class="valid-feedback">Kode dokter berhasil dimasukkan!</div>
                                            <div class="invalid-feedback">Masukkan kode dokter di sini.</div>
                                          </div>
                                          <div class="input-group input-group-static my-3" style="text-align: left;">
                                              <!--<label class="" for="editnama{{dokter.kode_dokter}}">Nama Dokter</label>-->
                                              <input type="text" id="editnama{{dokter.kode_dokter}}" class="form-control" name="nama_dokter" value="{{dokter.nama}}" required>
                                              <div class="valid-feedback">Nama dokter berhasil dimasukkan!</div>
                                              <div class="invalid-feedback">Masukkan nama dokter di sini</div>
                                          </div>
                                          <div class="input-group input-group-dynamic mb-4" style="text-align: left;">
                                            <span class="input-group-text" id="basic-addon1">@</span>
                                            <input type="number" id="editkomisi{{dokter.kode_dokter}}" class="form-control" placeholder="Komisi Dokter" aria-label="komisi_dokter" name="komisi_dokter" value="{{dokter.komisi_dokter}}" aria-describedby="basic-addon1" required>
                                            <div class="valid-feedback">Komisi berhasil dimasukkan!</div>
                                            <div class="invalid-feedback">Masukkan komisi dokter di sini</div>
                                          </div>
                                          <div class="text-center">
                                            <button type="submit" class="btn btn-round bg-gradient-info btn-lg w-100 mt-4 mb-0">Edit</button>
                                          </div>
                                        </form>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock content %}