bidang/urls.py
from django.urls import path
from .views import *

app_name= 'bidang'
urlpatterns = [
    path('', all_bidang, name='all_bidang'),
    path('add', add_bidang, name='add_bidang'),
    path('edit/<str:id>', edit_bidang, name='edit_bidang'),
    path('delete/<str:id>', delete_bidang, name='delete_bidang')
]

citra_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import pasien.urls
import nilai_normal.urls
import uji_lab.urls
import dokter.urls
import tester.urls
import pemeriksaan.urls
import bidang.urls
import uji_lab.urls
import hasil_pemeriksaan.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='pasien/', permanent=True)),
    path('home/', include(main.urls)),
    path('pasien/', include(pasien.urls)),
    path('nilai_normal/', include(nilai_normal.urls)),
    path('ujilab/', include(uji_lab.urls)),
    path('pemeriksaan/', include(pemeriksaan.urls)),
    path('dokter/', include(dokter.urls)),
    path('tester/', include(tester.urls)),
    path('bidang/', include(bidang.urls)),
    path('uji_lab/', include(uji_lab.urls)),
    path('hasil_pemeriksaan/', include(hasil_pemeriksaan.urls)),
    
]

dokter/urls.py
from django.urls import path
from .views import *

app_name= 'dokter'
urlpatterns = [
    path('', all_dokter, name='all_dokter'),
    path('add', add_dokter, name='add_dokter'),
    path('edit/<str:id>', edit_dokter, name='edit_dokter'),
    path('delete/<str:id>', delete_dokter, name='delete_dokter'),
    path('view/<str:id>', view_dokter, name='view_dokter'),
]

main/urls.py
from django.urls import path
from .views import *

app_name= 'main'
urlpatterns = [
    path('', index, name='index'),
]

pasien/urls.py
from django.urls import path
from .views import *

app_name= 'pasien'
urlpatterns = [
    path('', all_pasien, name='all_pasien'),
    path('add/', add_pasien, name='add_pasien'),
    path('edit/<str:id>', edit_pasien, name='edit_pasien'),
    path('delete/<str:id>', delete_pasien, name='delete_pasien'),
    path('view/<str:id>', view_pasien, name='view_pasien'),
]

tester/urls.py
from django.urls import path
from .views import *

app_name= 'tester'
urlpatterns = [
    path('', all_tester, name='all_tester'),
    path('add', add_tester, name='add_tester'),
    path('edit/<str:id>', edit_tester, name='edit_tester'),
    path('delete/<str:id>', delete_tester, name='delete_tester')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main.html')

main/templates/partial/navbar.html
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
        
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">
                {% block navbar_link %}
                    <!-- navbar title di sini -->
                {% endblock navbar_link %}
            </li>
        </ol>
        <h6 class="font-weight-bolder mb-0">
            {% block navbar_title %}
                <!-- navbar title di sini -->
            {% endblock navbar_title %}
        </h6>
        </nav>
    </div>
</nav>

main/templates/partial/sidebar.html
<!--Side Navbar-->
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3  bg-gradient-dark" id="sidenav-main">

    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
        
        <span class="ms-1 font-weight-bold text-white h5">Laboratorium Citra</span>
      </a>
    </div>
  
    <hr class="horizontal light mt-0 mb-2">
  
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        
  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'pasien:all_pasien' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">groups</i>
        </div>
      
      <span class="nav-link-text ms-1">Pasien</span>
    </a>
  </li>
  
    
  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'pemeriksaan:all_pemeriksaan' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">checklist</i>
        </div>
      
      <span class="nav-link-text ms-1">Pemeriksaan</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'uji_lab:all_uji_lab' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">science</i>
        </div>
      
      <span class="nav-link-text ms-1">Uji Laboratorium</span>
    </a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'nilai_normal:all_nilai_normal' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">lightbulb_circle</i>
        </div>
      
      <span class="nav-link-text ms-1">Nilai Normal</span>
    </a>
  </li>
  
    
  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'dokter:all_dokter' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">assignment_ind</i>
        </div>
      
      <span class="nav-link-text ms-1">Dokter</span>
    </a>
  </li>
  
    
  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'tester:all_tester' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">supervised_user_circle</i>
        </div>
      
      <span class="nav-link-text ms-1">Tester</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link text-white " href="{% url 'bidang:all_bidang' %}">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">view_module</i>
        </div>
      
      <span class="nav-link-text ms-1">Bidang</span>
    </a>
  </li>
  
    <!--
      <li class="nav-item mt-3">
        <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Account pages</h6>
      </li>
    
  <li class="nav-item">
    <a class="nav-link text-white " href="./profile.html">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">person</i>
        </div>
      
      <span class="nav-link-text ms-1">Profile</span>
    </a>
  </li>
  
    
  <li class="nav-item">
    <a class="nav-link text-white " href="./sign-in.html">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">login</i>
        </div>
      
      <span class="nav-link-text ms-1">Sign In</span>
    </a>
  </li>
  
    
  <li class="nav-item">
    <a class="nav-link text-white " href="./sign-up.html">
      
        <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
          <i class="material-icons opacity-10">assignment</i>
        </div>
      
      <span class="nav-link-text ms-1">Sign Up</span>
    </a>
  </li>-->
        
      </ul>
    </div>
    
    
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <div class="mx-3">
        <a class="btn btn-outline-primary mt-4 w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/overview/material-dashboard?ref=sidebarfree" type="button">Documentation</a>
        <a class="btn bg-gradient-primary w-100" href="https://www.creative-tim.com/product/material-dashboard-pro?ref=sidebarfree" type="button">Upgrade to pro</a>
      </div>
      
    </div>
    
</aside>

main/templates/partial/source.html
{% load static %}

 <!-- CSS only -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
 <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
 <link href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css" rel="stylesheet">
 <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
 <!-- {% static 'css/display_barang.css' %} -->
 <!-- Font Awesome Icons -->
 <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->
 <!-- CSS Files -->
 <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
 <link id="pagestyle" href="{% static 'css/test.css' %}" rel="stylesheet" />

 <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/searchBuilder.bootstrap5.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js?v=3.1.0' %}"></script>

    <script>
    $(document).ready(function() {
        $('#pasienTable').dataTable();
     } );
    </script>